---
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # https://github.com/dependabot/dependabot-core/issues/6528
    directory: "/apps/bun-nestjs-pq"
    schedule:
      interval: "monthly"
    groups:
      pg:
        patterns:
          - "pg"
          - "@types/pg"
  - package-ecosystem: "npm"
    directory: "/apps/nestjs"
    schedule:
      interval: "monthly"
    groups:
      pg:
        patterns:
          - "pg"
          - "@types/pg"
  - package-ecosystem: "npm"
    directory: "/apps/nextjs-example"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
