version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    extends:
      file: ../shared/docker-compose.yml
      service: db

volumes:
  postgres-data:
