---
name: Deploy
on:  # yamllint disable-line rule:truthy
  pull_request: # for testing, remove me
  push:
    branches:
      - main
    paths:
      - apps/nextjs-example/**

jobs:
  nextjs-example:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      APP_DIR: ./apps/nextjs-example
    steps:
      - uses: actions/checkout@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: >
          vercel pull --yes --environment=production --cwd $APP_DIR
          --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd $APP_DIR
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd $APP_DIR
